# =============================================
# Конфиг для pcb2gcode 2.5.0 (CNC 3018)
# Настройки под V-фрезу 60° 0.3 мм
# =============================================

### Основные параметры ###
front = test-F_Cu.gbr
drill = test-PTH.drl   # Сквозные отверстия
outline = test-Edge_Cuts.gbr
metric = 1
metricoutput = 1
basename = output
zero-start=true

zsafe=4
zchange=6

### Параметры сверловки ###
drill-feed = 30        # Скорость подачи при сверловке (мм/мин)
drill-speed = 12000    # Обороты шпинделя
zdrill = -1.4             # Высота быстрого подъема при сверловке
drill-side = front
onedrill = 0

### Параметры фрезы ###
mill-diameters = 0.25  # Диаметр кончика фрезы
milling-overlap = 25% # Критично для V-образной фрезы!

### Изоляция дорожек ###
#isolation-width = 0.3  # Минимальный зазор между дорожками (мм)
zwork = -0.018         # Стартовая глубина (начинать с малого!)
extra-passes = 0      # Без доп. проходов

### Скорости ###
mill-feed = 40       # Скорость подачи (мм/мин)
mill-speed = 12000    # Обороты шпинделя

### Оптимизации ###
vectorial = 1         # Точный векторный расчет
eulerian-paths = 1    # Исключение дублирующихся проходов
optimise = 0       # Оптимизация G-кода

### Вырезание контура ###
cutter-diameter = 2
zcut = -1.4
cut-feed = 30
cut-speed = 12000
cut-infeed = 0.8
bridgesnum = 0
#bridges = 3.0
cut-side = front

### Доп. безопасность ###
preserve-thermal-reliefs = 1  # Сохранять термобарьеры

## Не генерировать неподдерживаемые команды
nog64=true
nog91-1=true
nog81=true


nom6 = 1
