# =============================================
# Конфиг для pcb2gcode 2.5.0 (CNC 3018)
# Настройки под V-фрезу 60° 0.3 мм
# =============================================

### Основные параметры ###
front = testMicro-F_Cu.gbr
metric = 1
metricoutput = 1
basename = output
zero-start=true

zsafe=4
zchange=5

### Параметры фрезы ###
mill-diameters = 0.25  # Диаметр кончика фрезы
milling-overlap = 25% # Критично для V-образной фрезы!

### Изоляция дорожек ###
#isolation-width = 0.3  # Минимальный зазор между дорожками (мм)
zwork = -0.04         # Стартовая глубина (начинать с малого!)
extra-passes = 0      # Без доп. проходов

### Скорости ###
mill-feed = 100       # Скорость подачи (мм/мин)
mill-speed = 12000    # Обороты шпинделя

### Оптимизации ###
vectorial = 1         # Точный векторный расчет
eulerian-paths = 1    # Исключение дублирующихся проходов
optimise = 0       # Оптимизация G-кода

### Доп. безопасность ###
preserve-thermal-reliefs = 1  # Сохранять термобарьеры

## Не генерировать неподдерживаемые команды
nog64=true
nog91-1=true
